### ISSUE TITLE
Update existing, failing Sample Registration test

### ISSUE THREAD

**Issue by rosibaj** [icgc-argo/e2e-test#19]
The file format changed so the test is failing. 
Update the test so that it passes successfully. 

## Exit Criteria 
- [ ] Write the test 
- [ ] If UI changes are required (anchors etc) make the changes
- [ ] Make sure the test passes and get it to QA

**Comment by P-Saha** [comment]
https://github.com/icgc-argo/e2e-test/pull/22

First push for schema update
