### ISSUE TITLE
Implement Clinical Data Sign-off and Approval

### ISSUE THREAD

**Issue by rosibaj** [icgc-argo/e2e-test#26]
https://wiki.oicr.on.ca/display/icgcargotech/Automated+Testing+Plan 
test 7.0

- there are 2 flows : updates vs no updates
- summary modal should have correct update vs new summary 
- when update, get the approval message
- in the update case also add in as the DCC and and approve the submission
- when no update signoff and succeed thru to dashboard/toast

**Comment by P-Saha** [comment]
This test currently depends on this bug being fixed:
https://github.com/icgc-argo/platform-ui/issues/1044
Until then it will fail consistently, as expected.
