### ISSUE TITLE
Convert to TS: 5 tests 

### ISSUE THREAD

**Issue by rosibaj** [icgc-argo/e2e-test#38]
Convert to typescript: 

- [ ]  create program 
- [ ] edit program 
- [ ] clinical submission
- [ ] login 
- [ ] user profile

**Comment by rosibaj** [comment]
@ciaranschutte is there anything to test or deploy here?

**Comment by ciaranschutte** [comment]
need to apply fixes from before ts conversion

**Comment by ciaranschutte** [comment]
vpn making these quite a pain to test because of random network issues
